program LeitorBarrasProj;

uses
  System.StartUpCopy,
  FMX.Forms,
  LeitorBarras in 'LeitorBarras.pas' {formLeitorBarras},
  ZXing.BarcodeFormat in 'Classes\ZXing.BarcodeFormat.pas',
  ZXing.BaseLuminanceSource in 'Classes\ZXing.BaseLuminanceSource.pas',
  ZXing.Binarizer in 'Classes\ZXing.Binarizer.pas',
  ZXing.BinaryBitmap in 'Classes\ZXing.BinaryBitmap.pas',
  ZXing.BitSource in 'Classes\ZXing.BitSource.pas',
  ZXIng.ByteSegments in 'Classes\ZXIng.ByteSegments.pas',
  ZXing.CharacterSetECI in 'Classes\ZXing.CharacterSetECI.pas',
  ZXing.Common.BitArray in 'Classes\ZXing.Common.BitArray.pas',
  ZXing.Common.BitArrayImplementation in 'Classes\ZXing.Common.BitArrayImplementation.pas',
  ZXing.Common.BitMatrix in 'Classes\ZXing.Common.BitMatrix.pas',
  ZXing.Common.Detector.MathUtils in 'Classes\ZXing.Common.Detector.MathUtils.pas',
  ZXing.Common.Detector.WhiteRectangleDetector in 'Classes\ZXing.Common.Detector.WhiteRectangleDetector.pas',
  ZXing.Common.DetectorResult in 'Classes\ZXing.Common.DetectorResult.pas',
  ZXing.Common.GridSampler in 'Classes\ZXing.Common.GridSampler.pas',
  ZXing.Common.PerspectiveTransform in 'Classes\ZXing.Common.PerspectiveTransform.pas',
  ZXing.Common.ReedSolomon.GenericGF in 'Classes\ZXing.Common.ReedSolomon.GenericGF.pas',
  ZXing.Common.ReedSolomon.ReedSolomonDecoder in 'Classes\ZXing.Common.ReedSolomon.ReedSolomonDecoder.pas',
  ZXing.Datamatrix.DataMatrixReader in 'Classes\ZXing.Datamatrix.DataMatrixReader.pas',
  ZXing.Datamatrix.Internal.BitMatrixParser in 'Classes\ZXing.Datamatrix.Internal.BitMatrixParser.pas',
  ZXing.Datamatrix.Internal.DataBlock in 'Classes\ZXing.Datamatrix.Internal.DataBlock.pas',
  ZXing.Datamatrix.Internal.DecodedBitStreamParser in 'Classes\ZXing.Datamatrix.Internal.DecodedBitStreamParser.pas',
  ZXing.Datamatrix.Internal.Decoder in 'Classes\ZXing.Datamatrix.Internal.Decoder.pas',
  ZXing.Datamatrix.Internal.Detector in 'Classes\ZXing.Datamatrix.Internal.Detector.pas',
  ZXing.Datamatrix.Internal.Version in 'Classes\ZXing.Datamatrix.Internal.Version.pas',
  ZXing.DecodeHintType in 'Classes\ZXing.DecodeHintType.pas',
  ZXing.DecoderResult in 'Classes\ZXing.DecoderResult.pas',
  ZXing.DefaultGridSampler in 'Classes\ZXing.DefaultGridSampler.pas',
  ZXing.EncodeHintType in 'Classes\ZXing.EncodeHintType.pas',
  ZXing.GlobalHistogramBinarizer in 'Classes\ZXing.GlobalHistogramBinarizer.pas',
  ZXing.Helpers in 'Classes\ZXing.Helpers.pas',
  ZXing.HybridBinarizer in 'Classes\ZXing.HybridBinarizer.pas',
  ZXing.InvertedLuminanceSource in 'Classes\ZXing.InvertedLuminanceSource.pas',
  ZXing.LuminanceSource in 'Classes\ZXing.LuminanceSource.pas',
  ZXing.MultiFormatReader in 'Classes\ZXing.MultiFormatReader.pas',
  ZXing.OneD.Code39Reader in 'Classes\ZXing.OneD.Code39Reader.pas',
  ZXing.OneD.Code93Reader in 'Classes\ZXing.OneD.Code93Reader.pas',
  ZXing.OneD.Code128Reader in 'Classes\ZXing.OneD.Code128Reader.pas',
  ZXing.OneD.EAN8Reader in 'Classes\ZXing.OneD.EAN8Reader.pas',
  ZXing.OneD.EAN13Reader in 'Classes\ZXing.OneD.EAN13Reader.pas',
  ZXing.OneD.EANManufacturerOrgSupport in 'Classes\ZXing.OneD.EANManufacturerOrgSupport.pas',
  ZXing.OneD.ITFReader in 'Classes\ZXing.OneD.ITFReader.pas',
  ZXing.OneD.OneDReader in 'Classes\ZXing.OneD.OneDReader.pas',
  ZXing.OneD.UPCAReader in 'Classes\ZXing.OneD.UPCAReader.pas',
  ZXing.OneD.UPCEANExtension2Support in 'Classes\ZXing.OneD.UPCEANExtension2Support.pas',
  ZXing.OneD.UPCEANExtension5Support in 'Classes\ZXing.OneD.UPCEANExtension5Support.pas',
  ZXing.OneD.UPCEANExtensionSupport in 'Classes\ZXing.OneD.UPCEANExtensionSupport.pas',
  ZXing.OneD.UPCEANReader in 'Classes\ZXing.OneD.UPCEANReader.pas',
  ZXing.OneD.UPCEReader in 'Classes\ZXing.OneD.UPCEReader.pas',
  ZXing.PlanarYUVLuminanceSource in 'Classes\ZXing.PlanarYUVLuminanceSource.pas',
  ZXing.QrCode.Internal.AlignmentPattern in 'Classes\ZXing.QrCode.Internal.AlignmentPattern.pas',
  ZXing.QrCode.Internal.AlignmentPatternFinder in 'Classes\ZXing.QrCode.Internal.AlignmentPatternFinder.pas',
  ZXing.QrCode.Internal.AlignmentPatternImplementation in 'Classes\ZXing.QrCode.Internal.AlignmentPatternImplementation.pas',
  ZXing.QrCode.Internal.BitMatrixParser in 'Classes\ZXing.QrCode.Internal.BitMatrixParser.pas',
  ZXing.QrCode.Internal.DataBlock in 'Classes\ZXing.QrCode.Internal.DataBlock.pas',
  ZXing.QrCode.Internal.DataMask in 'Classes\ZXing.QrCode.Internal.DataMask.pas',
  ZXing.QrCode.Internal.DecodedBitStreamParser in 'Classes\ZXing.QrCode.Internal.DecodedBitStreamParser.pas',
  ZXing.QrCode.Internal.Decoder in 'Classes\ZXing.QrCode.Internal.Decoder.pas',
  ZXing.QrCode.Internal.Detector in 'Classes\ZXing.QrCode.Internal.Detector.pas',
  ZXing.QrCode.Internal.ErrorCorrectionLevel in 'Classes\ZXing.QrCode.Internal.ErrorCorrectionLevel.pas',
  ZXing.QrCode.Internal.FinderPattern in 'Classes\ZXing.QrCode.Internal.FinderPattern.pas',
  ZXing.QrCode.Internal.FinderPatternFinder in 'Classes\ZXing.QrCode.Internal.FinderPatternFinder.pas',
  ZXing.QrCode.Internal.FinderPatternImplementation in 'Classes\ZXing.QrCode.Internal.FinderPatternImplementation.pas',
  ZXing.QrCode.Internal.FinderPatternInfo in 'Classes\ZXing.QrCode.Internal.FinderPatternInfo.pas',
  ZXing.QrCode.Internal.FormatInformation in 'Classes\ZXing.QrCode.Internal.FormatInformation.pas',
  ZXing.QrCode.Internal.Mode in 'Classes\ZXing.QrCode.Internal.Mode.pas',
  ZXing.QrCode.Internal.QRCodeDecoderMetaData in 'Classes\ZXing.QrCode.Internal.QRCodeDecoderMetaData.pas',
  ZXing.QrCode.Internal.Version in 'Classes\ZXing.QrCode.Internal.Version.pas',
  ZXing.QrCode.QRCodeReader in 'Classes\ZXing.QrCode.QRCodeReader.pas',
  ZXing.Reader in 'Classes\ZXing.Reader.pas',
  ZXing.ReadResult in 'Classes\ZXing.ReadResult.pas',
  ZXing.ResultMetadataType in 'Classes\ZXing.ResultMetadataType.pas',
  ZXing.ResultPoint in 'Classes\ZXing.ResultPoint.pas',
  ZXing.ResultPointImplementation in 'Classes\ZXing.ResultPointImplementation.pas',
  ZXing.RGBLuminanceSource in 'Classes\ZXing.RGBLuminanceSource.pas',
  ZXing.ScanManager in 'Classes\ZXing.ScanManager.pas',
  ZXing.StringUtils in 'Classes\ZXing.StringUtils.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.CreateForm(TformLeitorBarras, formLeitorBarras);
  Application.Run;
end.
